<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit02634233deda38b44ddaee6c19b0e998
{
    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'StringTemplate\\Test' => 
            array (
                0 => __DIR__ . '/..' . '/nicmart/string-template/tests',
            ),
            'StringTemplate' => 
            array (
                0 => __DIR__ . '/..' . '/nicmart/string-template/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit02634233deda38b44ddaee6c19b0e998::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
